Feature/JoinPage
DangGeuneDaong/Frontend pull request #9
Opened 2023-06-08 09:58 UTC by eeseohyun

## 😀 개요

유저들의 정보를 받아오는 회원가입 페이지 구현

## 🛠️ 작업사항
1. 유효성 검사
=> 모든 값이 `true` 라면 버튼을 활성화
- 비밀번호 : 영문, 숫자 포함 6자 이상    
    `/^(?=.*?[A-Za-z])(?=.*?[0-9]).{6,}$/`
- 아이디 : 대소문자 또는 숫자 4글자 이상 12글자 이하
`/*^*[a-zA-Z0-9]{4,12}*$*/`
- 닉네임 : 2글자 이상 10글자 이하

2. 주소 정보 불러오기
- `react-daum-postcode` 이용
- 상세 주소 정보까지는 받아오지 않음❌
![image](https://github.com/DangGeuneDaong/Frontend/assets/87015084/88a231ee-9cb5-4096-8859-e4639a4c60c7)
)
- 추가 반응형 구현 필요

## 🧩 변경로직

- 모달창 => 팝업으로 변경
![image](https://github.com/DangGeuneDaong/Frontend/assets/87015084/3492a1c8-2f6e-4cd3-ba3a-14c03927a2fe)

## 🤔 사용방법

## 기타

2023-06-08 10:43 UTC, geniee1220 reviewed
지금 Develop 브랜치에 있는 내용이 새로운 파일로 잡히고 있어서 Git Graph로 확인해봤는데 Develop 브랜치가 통합이 안 된거 같아요! (PR #6) 확인 한 번만 부탁드립니다 🙌

2023-06-08 17:29 UTC, geniee1220 approved these changes

2023-06-09 01:23 UTC, minkyuu approved these changes
react hook form 사용하니까 확실히 코드가 많이 줄어드네요 😯

2023-06-09 01:57 UTC, Whale2200d approved these changes

2023-06-09 01:57 UTC, minkyuu requested changes
react hook form 사용하니까 확실히 코드가 많이 줄어드네요 😯

추가 : main 브랜치 -> **develop 브랜치**로 변경만 해보면 될 것 같아요!

2023-06-09 01:59 UTC, geniee1220 approved these changes

2023-06-16 00:07 UTC, minkyuu approved these changes

2023-06-26 06:44 UTC, merged